baseurl = "/"
title = "Compute Canada HSS series 2022"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

# pygmentsstyle = "b2"
# pygmentscodefences = true
# pygmentscodefencesguesssyntax = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    style = "manni"   # Chroma Style Gallery https://xyproto.github.io/splash/docs/longer/all.html

[params]
    author = "Compute Canada"
    description = ""
    keywords = ""
    info = "HSS series 2022"
    wgavatar = "/images/cc_white_removed_medium.png"
    favicon_32 = "/images/favicon.png"

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false
    since = 2020

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "light"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            # [[languages.en.menu.main]]
            # name = "Intro"
            # weight = 1
            # url = "bash-menu"

            # [[languages.en.menu.main]]
            # name = "Cloud"
            # weight = 2
            # url = "git"

            # [[languages.en.menu.main]]
            # name = "DMPs"
            # weight = 3
            # url = "hpc-menu"

            # [[languages.en.menu.main]]
            # name = "ProjectManagement"
            # weight = 4
            # url = "python-menu"

	    # [[languages.en.menu.main]]
	    # name = "Tools"
	    # weight = 5
	    # url  = "pytorch"

	    # [[languages.en.menu.main]]
	    # name = "CLI"
	    # weight = 6
	    # url  = "chapel-menu"

	    # [[languages.en.menu.main]]
	    # name = "Photogrammetry"
	    # weight = 7
	    # url  = "julia"

	    # [[languages.en.menu.main]]
	    # name = "WebScraping"
	    # weight = 8
	    # url  = "vis-menu"
